//-----------------------------------------------------------------------------------
// This file is generated by CMake
//-----------------------------------------------------------------------------------

#pragma once

#include <string>

using namespace std;

namespace AppDetails
{
    const string APP_NAME           = "BannerText";
    const string APP_DESCRIPTION    = "Show Banner messages to the console";
    const string APP_COMPANY_NAME   = "";
    const string APP_COPYRIGHT      = "";
    const string APP_VERSION        = "1.0";
    const string APP_VERSION_FULL   = "1.0.0.0";
    const string APP_VERSION_BEST   = "1.0";
    const string APP_VERSION_HEADER = APP_NAME + " " + APP_VERSION_BEST;
    const string APP_HEADER         = APP_NAME + " v" + APP_VERSION_BEST + " - " + APP_DESCRIPTION;
}
