//-----------------------------------------------------------------------------------
// This file is generated by CMake
//-----------------------------------------------------------------------------------

#pragma once

#include <string>

using namespace std;

namespace AppDetails
{
    const string APP_NAME           = "dnx_utilities";
    const string APP_DESCRIPTION    = "";
    const string APP_COMPANY_NAME   = "DNX Solutions";
    const string APP_COPYRIGHT      = "Copyright (c) DNX Solutions 2011-2025";
    const string APP_VERSION        = "";
    const string APP_VERSION_FULL   = "1.0.0.0";
    const string APP_VERSION_BEST   = "1.0";
    const string APP_VERSION_HEADER = APP_NAME + " " + APP_VERSION_BEST;
    const string APP_HEADER         = APP_NAME + " v" + APP_VERSION_BEST + " - " + APP_DESCRIPTION;
}
