include("${CMAKE_SOURCE_DIR}/cmake/common.cmake")

########################################################################################################################
## Functions
########################################################################################################################

function(WriteAppDetailsHeader)
    set(filename ${PROJECT_SOURCE_DIR}/AppDetails.h)
    StatusMessage("Writing: ${filename}")

    BuildBestVersionNumber()

    file(WRITE
            "${filename}"
            "//-----------------------------------------------------------------------------------\n"
            "// This file is generated by CMake\n"
            "//-----------------------------------------------------------------------------------\n"
            "\n"
            "#pragma once\n"
            "\n"
            "#include <string>\n"
            "\n"
            "using namespace std;\n"
            "\n"
            "namespace AppDetails\n"
            "{\n"
            "    const string APP_NAME           = \"${PROJECT_NAME}\";\n"
            "    const string APP_DESCRIPTION    = \"${PROJECT_DESCRIPTION}\";\n"
            "    const string APP_COMPANY_NAME   = \"${APP_COMPANY_NAME}\";\n"
            "    const string APP_COPYRIGHT      = \"${APP_COPYRIGHT}\";\n"
            "    const string APP_VERSION        = \"${PROJECT_VERSION}\";\n"
            "    const string APP_VERSION_FULL   = \"${APP_VERSION_FULL}\";\n"
            "    const string APP_VERSION_BEST   = \"${APP_VERSION_BEST}\";\n"
            "    const string APP_VERSION_HEADER = APP_NAME + \" \" + APP_VERSION_BEST;\n"
            "    const string APP_HEADER         = APP_NAME + \" v\" + APP_VERSION_BEST + \" - \" + APP_DESCRIPTION;\n"
            "}\n"
    )
endfunction()

function(WriteAppDetailsResources)
    set(filename ${PROJECT_SOURCE_DIR}/AppVersionInfo.rc)
    StatusMessage("Writing: ${filename}")

    BuildBestVersionNumber()

    set(ICON_DEFINITION "")
    if(NOT "${APP_ICON_FILENAME}" STREQUAL "")
        set(ICON_DEFINITION "5555 ICON DISCARDABLE \"${APP_ICON_FILENAME}\"")
    endif()

    file(WRITE
            "${filename}"
            "//-----------------------------------------------------------------------------------\n"
            "// This file is generated by CMake\n"
            "//-----------------------------------------------------------------------------------\n"
            "\n"
            "//\n"
            "// Include the necessary resources\n"
            "//\n"
            "#include <winver.h>\n"
            "#include <ntdef.h>\n"
            "\n"
            "#ifdef RC_INVOKED\n"
            "\n"
            "//\n"
            "// Set up debug information\n"
            "//\n"
            "#if DBG\n"
            "#define VER_DBG VS_FF_DEBUG\n"
            "#else\n"
            "#define VER_DBG 0\n"
            "#endif\n"
            "\n"
            "// ------- asset info -------------------------------------------------------\n"
            "\n"
            "${ICON_DEFINITION}\n"
            "\n"
            "// ------- version info -------------------------------------------------------\n"
            "\n"
            "VS_VERSION_INFO VERSIONINFO\n"
            "FILEVERSION             ${APP_RESOURCE_VERSION_FULL}\n"
            "PRODUCTVERSION          ${APP_RESOURCE_VERSION_FULL}\n"
            "FILEFLAGSMASK           VS_FFI_FILEFLAGSMASK\n"
            "FILEFLAGS               VER_DBG\n"
            "FILEOS                  VOS_NT\n"
            "FILETYPE                VFT_DRV\n"
            "FILESUBTYPE             VFT2_DRV_SYSTEM\n"
            "BEGIN\n"
            "    BLOCK \"StringFileInfo\"\n"
            "    BEGIN\n"
            "        BLOCK \"040904b0\"\n"
            "        BEGIN\n"
            "            VALUE \"Comments\",         \"${PROJECT_DESCRIPTION}\"\n"
            "            VALUE \"CompanyName\",      \"${APP_COMPANY_NAME}\"\n"
            "            VALUE \"FileDescription\",  \"${PROJECT_DESCRIPTION}\"\n"
            "            VALUE \"FileVersion\",      \"v${APP_VERSION_FULL}\"\n"
            "            VALUE \"InternalName\",     \"${PROJECT_NAME}\"\n"
            "            VALUE \"LegalCopyright\",   \"${APP_COPYRIGHT}\"\n"
            "            VALUE \"OriginalFilename\", \"${PROJECT_NAME}\"\n"
            "            VALUE \"ProductName\",      \"${PROJECT_NAME}\"\n"
            "            VALUE \"ProductVersion\",   \"v${APP_VERSION_FULL}\"\n"
            "            VALUE \"BuildConfig\",      \"${CMAKE_BUILD_TYPE}\"\n"
            "        END\n"
            "    END\n"
            "    BLOCK \"VarFileInfo\"\n"
            "    BEGIN\n"
            "        VALUE \"Translation\", 0x0409,1200\n"
            "    END\n"
            "END\n"
            "#endif\n"
    )
endfunction()


########################################################################################################################
## Macros
########################################################################################################################

macro(SetProjectCompanyName companyName)
    set(APP_COMPANY_NAME ${companyName})
endmacro()

macro(SetProjectCopyright copyright)
    string(TIMESTAMP currentYear "%Y")
    string(REPLACE "{CURRENTYEAR}" "${currentYear}" appCopyright "${copyright}")
    set(APP_COPYRIGHT "${appCopyright}")
endmacro()

macro(SetProjectIcon iconFileName)
    set(APP_ICON_FILENAME ${iconFileName})
endmacro()

macro(BeginProjectCPP projectName version description)
    if (${description} EQUAL "")
        set(description, ${PROJECT_NAME})
    endif()
    project(${projectName}
            VERSION ${version}
            DESCRIPTION "${description}"
    )
    StartProject()
endmacro()

macro(CollectSourceFilesCPP)
    file(GLOB_RECURSE source_files
            ${PROJECT_SOURCE_DIR}/*.cpp
            ${PROJECT_SOURCE_DIR}/*.h
            ${PROJECT_SOURCE_DIR}/*.hpp
    )
    ShowFiles("Source" "${source_files}")
endmacro()

macro(CollectResourceFilesCPP)
    file(GLOB_RECURSE resource_files
            *.rc
    )
    ShowFiles("Resource" "${resource_files}")
endmacro()

macro(BuildBestVersionNumber)
    set(major ${PROJECT_VERSION_MAJOR})
    set(minor ${PROJECT_VERSION_MINOR})
    set(patch ${PROJECT_VERSION_PATCH})
    set(tweak ${PROJECT_VERSION_TWEAK})

    if(NOT major OR major STREQUAL "")
        set(major 1)
    endif()
    if(NOT minor OR minor STREQUAL "")
        set(minor 0)
    endif()
    if(NOT patch OR patch STREQUAL "")
        set(patch 0)
    endif()
    if(NOT tweak OR tweak STREQUAL "")
        set(tweak 0)
    endif()

    # Set Full Version number
    set(APP_VERSION_FULL "${major}.${minor}.${patch}.${tweak}")
    string(REPLACE "." "," APP_RESOURCE_VERSION_FULL "${APP_VERSION_FULL}")

    # Set Best Version number
    set(APP_VERSION_BEST "${major}.${minor}")
    if(patch GREATER 0)
        set(APP_VERSION_BEST "${major}.${minor}.${patch}")
        if(tweak GREATER 0)
            set(APP_VERSION_BEST "${major}.${minor}.${patch}.${tweak}")
        endif()
    endif ()
endmacro()

########################################################################################################################
## Initialisation
########################################################################################################################
StatusMessage("C++ : ${CMAKE_CXX_COMPILER_ID} v${CMAKE_CXX_COMPILER_VERSION} : ${PROJECT_NAME}")
